POST http://localhost:8080/posts
Content-Type: application/json

{
    "teaser": "Why are images not working",
    "title": "Creating A Document From Server",
    "img": "justanormalimagefile.jpeg",
    "imagecredit": "justanormalimagefile",
    "text": "Some markdown words nothing special yet"
  }